# Generated by Django 4.1.3 on 2022-12-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'verbose_name': 'KYC', 'verbose_name_plural': 'KYCs'},
        ),
        migrations.AlterField(
            model_name='kyc',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='account.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_front_view',
            field=models.FileField(upload_to='kyc/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
