# Generated by Django 4.1.3 on 2022-12-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_kyc_options_alter_kyc_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id_front_view',
            field=models.FileField(upload_to='kyc/'),
        ),
    ]
