# Generated by Django 4.1.3 on 2022-12-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_kyc_id_front_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='id_front_view',
            field=models.FileField(upload_to='kyc/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
