# Generated by Django 4.1.6 on 2023-08-25 17:17

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_main_balance_account_crypto_main_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('currency_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('GBP', 'GBP')], default='XYZ', editable=False, max_length=3)),
                ('currency', djmoney.models.fields.MoneyField(blank=True, currency_choices=(('USD', 'USD'), ('GBP', 'GBP')), decimal_places=2, default=Decimal('0'), max_digits=19, null=True)),
            ],
        ),
    ]
