# Generated by Django 4.1.6 on 2023-08-27 13:00

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_fiatcurrency_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatcurrency',
            name='currency',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=(('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')), decimal_places=2, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='currency_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='XYZ', editable=False, max_length=3),
        ),
    ]
