# Generated by Django 4.1.6 on 2023-08-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_fiatportfolio_balance_fiatportfolio_balance_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatportfolio',
            name='name',
        ),
    ]
