# Generated by Django 4.1.6 on 2023-08-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_fiatportfolio_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='CryptoPortfolio',
        ),
    ]
