# Generated by Django 4.1.6 on 2023-08-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_portfolio_cryptoportfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatcurrency',
            options={'verbose_name_plural': 'Fiat Currencies'},
        ),
    ]
