# Generated by Django 4.1.6 on 2023-08-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_fiatcurrency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
    ]
