# Generated by Django 4.1.6 on 2023-09-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_paymentmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='is_crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='wallet_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
