# Generated by Django 4.1.6 on 2023-09-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_paymentmethods_is_crypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='for_withdrawal',
            field=models.BooleanField(default=False),
        ),
    ]
