# Generated by Django 4.1.6 on 2023-09-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_paymentmethods_for_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='transfer_access',
            field=models.BooleanField(default=False),
        ),
    ]
