# Generated by Django 4.1.6 on 2023-09-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_paymentmethods_transfer_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='for_deposit',
            field=models.BooleanField(default=False),
        ),
    ]
