# Generated by Django 4.1.6 on 2023-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_paymentmethods_transaction_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethods',
            old_name='transaction_message',
            new_name='deposit_transaction_message',
        ),
    ]
