# Generated by Django 4.1.6 on 2023-10-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_fiatportfolio_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatportfolio',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_portfolio', to='account.fiatcurrency'),
        ),
    ]
