# Generated by Django 4.1.6 on 2023-10-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_fiatportfolio_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatportfolio',
            name='note',
        ),
    ]
