# Generated by Django 4.1.6 on 2023-10-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_fiatportfolio_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='withdrawal_transaction_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
