# Generated by Django 4.1.6 on 2023-10-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='name',
        ),
    ]
