# Generated by Django 4.1.6 on 2023-10-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_exchangerate_exchange_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='exchange_fee',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='exchange_fee_currency',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='exchange_fee_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
