# Generated by Django 4.1.6 on 2023-10-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_remove_exchangerate_exchange_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='exchange_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
