# Generated by Django 4.1.6 on 2023-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_account_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fiat_main_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fiat_main_balance_currency',
        ),
        migrations.AddField(
            model_name='fiatcurrency',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='fiatportfolio',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
