# Generated by Django 4.1.6 on 2024-03-24 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_fiatportfolio_freeze_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_ME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID.me',
                'verbose_name_plural': 'ID.me',
            },
        ),
    ]
