# Generated by Django 4.1.6 on 2024-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_id_me_link_authorizationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationtoken',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
