# Generated by Django 4.1.6 on 2024-03-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_alter_authorizationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationtoken',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
