# Generated by Django 4.1.6 on 2024-03-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_authorizationtoken_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_me',
            name='link',
        ),
    ]
