# Generated by Django 4.1.6 on 2024-03-30 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_next_of_kin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('freeze', models.BooleanField(default=False)),
                ('card_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.card_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
        ),
    ]
