# Generated by Django 4.1.6 on 2024-03-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_alter_cards_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fiatcurrency'),
        ),
    ]
