# Generated by Django 4.1.6 on 2024-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_cards_balance_cards_balance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
