# Generated by Django 4.1.6 on 2024-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_alter_cards_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='freeze',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
