# Generated by Django 4.1.6 on 2024-04-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationtoken',
            name='otp_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
