# Generated by Django 4.1.6 on 2024-04-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_id_me_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_me',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
