# Generated by Django 4.1.6 on 2024-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_id_me_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_me',
            name='otp_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
