# Generated by Django 4.1.6 on 2024-05-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_id_me_otp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_type',
            name='card_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
