# Generated by Django 4.1.6 on 2024-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_paymentmethods_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
