# Generated by Django 4.1.6 on 2024-06-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_paymentmethods_logo_paymentmethods_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='notice',
        ),
    ]
