# Generated by Django 4.1.6 on 2024-06-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_remove_paymentmethods_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='supporting_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fiatcurrency'),
        ),
    ]
