# Generated by Django 4.1.6 on 2024-07-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='country',
        ),
    ]
