# Generated by Django 4.1.6 on 2024-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_remove_paymentmethods_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='banks',
            field=models.ManyToManyField(blank=True, null=True, to='account.banks'),
        ),
    ]
