# Generated by Django 4.1.6 on 2024-07-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_banks_supporting_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='supporting_currency',
        ),
        migrations.AddField(
            model_name='banks',
            name='supporting_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fiatcurrency'),
        ),
    ]
