# Generated by Django 4.1.6 on 2024-08-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_remove_banks_supporting_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='banks',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings Account', 'Savings Account'), ('Checking Account', 'Checking Account'), ('Joint-checking Account', 'Joint-checking Account'), ('Business Account', 'Business Account')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='JointAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_holders', models.ManyToManyField(blank=True, related_name='joint_accounts', to='account.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_account', to='account.account')),
            ],
        ),
    ]
