# Generated by Django 4.1.6 on 2024-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_remove_paymentmethods_banks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointaccount',
            name='account_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
