# Generated by Django 4.1.6 on 2024-08-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_alter_jointaccount_account_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointaccount',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
