# Generated by Django 4.1.6 on 2024-08-10 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_jointaccount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joint_Account_KYC',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100, null=True)),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode/Zipcode')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('town_city', models.CharField(max_length=150, verbose_name='Town/City')),
                ('state', models.CharField(max_length=150, verbose_name='State')),
                ('document_type', models.CharField(choices=[('Driver License', 'Driver License'), ('National ID', 'National ID'), ('Passport', 'Passport')], max_length=50, null=True)),
                ('id_front_view', models.FileField(null=True, upload_to='kyc/%Y-%m-%d/')),
                ('id_back_view', models.FileField(blank=True, null=True, upload_to='kyc/%Y-%m-%d/')),
                ('ssn', models.FileField(blank=True, null=True, upload_to='kyc/%Y-%m-%d/')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='account.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Joint Account KYC',
                'verbose_name_plural': 'Joint Account KYC',
            },
        ),
    ]
