# Generated by Django 4.1.6 on 2024-08-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_joint_account_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joint_account_kyc',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='account.account', verbose_name='Client'),
        ),
    ]
