# Generated by Django 4.1.6 on 2024-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_alter_joint_account_kyc_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint_account_kyc',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
