# Generated by Django 4.1.6 on 2024-08-11 11:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_joint_account_kyc_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint_account_kyc',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
