# Generated by Django 4.1.6 on 2024-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_joint_account_kyc_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='joint_account_kyc',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
    ]
