# Generated by Django 4.1.6 on 2024-08-11 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_joint_account_kyc_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='joint_account', to='account.account'),
        ),
    ]
