# Generated by Django 4.1.6 on 2024-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_jointaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='joint_account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
