# Generated by Django 4.1.6 on 2024-09-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_cardtracking_cardtrackinghistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardTracking',
            new_name='Card_Tracking',
        ),
    ]
