# Generated by Django 4.1.6 on 2025-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_card_trackings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Savings Account', 'Savings Account'), ('Investment Account', 'Investment Account'), ('Checking Account', 'Checking Account'), ('Joint-checking Account', 'Joint-checking Account'), ('Business Account', 'Business Account')], max_length=200, null=True),
        ),
    ]
