# Generated by Django 4.1.6 on 2025-08-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='image',
            field=models.ImageField(blank=True, default='avatars/avatar.jpg', upload_to='invest/image'),
        ),
    ]
