# Generated by Django 4.1.6 on 2023-10-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
