# Generated by Django 4.1.6 on 2023-10-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_transactions_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='card_name',
            new_name='card_holder',
        ),
    ]
