# Generated by Django 4.1.6 on 2023-10-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
