# Generated by Django 4.1.6 on 2023-10-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_transactions_month_alter_transactions_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='payment_description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
