# Generated by Django 4.1.6 on 2023-10-05 11:37

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_transactions_fees_transactions_fees_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='fees',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
