# Generated by Django 4.1.6 on 2023-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_alter_transactions_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
