# Generated by Django 4.1.6 on 2023-10-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_transactions_balance_after_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='balance_after_fee',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='balance_after_fee_currency',
        ),
    ]
