# Generated by Django 4.1.6 on 2023-10-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_remove_transactions_balance_after_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('Awaiting Approval', 'Awaiting Approval'), ('Successful', 'Successful'), ('Received', 'Received'), ('failed', 'failed'), ('In Progress', 'In Progress'), ('Declined', 'Declined')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund')], max_length=200),
        ),
    ]
