# Generated by Django 4.1.6 on 2023-10-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_alter_transactions_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CREDIT', 'Credit')], max_length=200),
        ),
    ]
