# Generated by Django 4.1.6 on 2023-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CREDIT', 'Credit'), ('EXCHANGE', 'Exchange')], max_length=200),
        ),
    ]
