# Generated by Django 4.1.6 on 2024-03-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='sort_code',
            new_name='swift_code',
        ),
    ]
