# Generated by Django 4.1.6 on 2024-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0020_rename_sort_code_transactions_swift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CREDIT', 'Credit'), ('EXCHANGE', 'Exchange'), ('CARD FUNDING', 'CARD FUNDING'), ('CARD WITHDRAWAL', 'CARD WITHDRAWAL')], max_length=200),
        ),
    ]
