# Generated by Django 4.1.6 on 2024-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0022_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CREDIT', 'Credit'), ('EXCHANGE', 'Exchange'), ('CARD FUNDING', 'CARD FUNDING'), ('CARD WITHDRAWAL', 'CARD WITHDRAWAL'), ('Card Delivery Fee', 'Card Delivery Fee')], max_length=200),
        ),
    ]
