# Generated by Django 4.1.6 on 2025-08-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0102_investment_image'),
        ('transaction', '0023_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='investment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.investment'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CREDIT', 'Credit'), ('EXCHANGE', 'Exchange'), ('CARD FUNDING', 'CARD FUNDING'), ('CARD WITHDRAWAL', 'CARD WITHDRAWAL'), ('Card Delivery Fee', 'Card Delivery Fee'), ('INVESTMENT', 'INVESTMENT')], max_length=200),
        ),
    ]
