# Generated by Django 4.1.6 on 2025-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_transactions_investment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CREDIT', 'Credit'), ('EXCHANGE', 'Exchange'), ('CARD FUNDING', 'CARD FUNDING'), ('CARD WITHDRAWAL', 'CARD WITHDRAWAL'), ('Card Delivery Fee', 'Card Delivery Fee'), ('INVESTMENT', 'INVESTMENT'), ('ROI', 'ROI')], max_length=200),
        ),
    ]
