# Generated by Django 4.1.6 on 2025-09-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0026_custominvestment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custominvestment',
            old_name='name',
            new_name='investment',
        ),
    ]
