# Generated by Django 4.1.6 on 2023-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=500)),
                ('logo', models.ImageField(upload_to='company_profile')),
                ('favicon', models.ImageField(upload_to='company_profile')),
                ('support_email', models.EmailField(max_length=200)),
                ('forwarding_email', models.EmailField(max_length=200)),
            ],
        ),
    ]
