# Generated by Django 4.1.6 on 2023-10-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='logo',
            new_name='company_logo',
        ),
    ]
